In [ ]:
# Create tensors of different shapes and dtypes.
# Make 1D, 2D, and 3D tensors; inspect shape, dtype, and device.
# Practice indexing and slicing.
# Extract single values, rows, columns, and submatrices.
# Apply basic tensor operations.
# Try +, -, *, /, @, exp(), mean(), max(), sqrt().
# Compare tensor operations with NumPy.
# Convert NumPy arrays to tensors and back; note dtype differences.
# Test torch.tensor(), FloatTensor(), and from_numpy().
# Observe copy vs shared memory behavior.
# Do in-place and out-of-place operations.
# Compare X.relu_() vs X.relu(), X += 1 vs X = X + 1.
# Move tensors between CPU and GPU.
# Use .to(device), .cpu(), .cuda(), and check .device.
# Benchmark CPU vs GPU matrix multiplication.
# Test with small and large matrices and observe when GPU helps.
# Build a simple autograd example.
# Compute x**2, call backward(), and inspect x.grad.
# Run a full gradient descent loop on one variable.
# Minimize f(x)=x^2 and watch x move toward 0.
# Use no_grad() correctly.
# Update parameters inside with torch.no_grad():.
# Use detach() and compare it with no_grad().
# Check how detached tensors share memory.
# Reset gradients with zero_().
# Show what happens if you do not clear gradients between iterations.
# Trigger and fix an in-place autograd error.
# Try modifying an intermediate tensor before backward().
# Write a tiny training loop from scratch.
# Forward pass → loss → backward pass → update → zero gradients.

# [pending]
# Medium answers, 100–250 words

# Use these only when you need deeper understanding.

# Explain the tensor API in PyTorch and how it resembles NumPy.
# Describe how PyTorch uses dynamic computation graphs.
# Explain CPU vs GPU execution in PyTorch and why data transfer matters.
# Describe the autograd workflow using x ** 2 as an example.
# Explain why gradient accumulation can cause bugs in training.
# Compare in-place and out-of-place operations with examples.
# Explain why some in-place operations break backpropagation.
# Describe the role of grad_fn in computation graphs.
# Explain how from_numpy() differs from torch.tensor(np_array).
# Explain the full training loop for a one-variable gradient descent problem.
# Long answers, 250–300 words

# Use these only if the exam or oral revision demands detailed explanation.

# Discuss PyTorch as a deep learning framework: tensors, GPU support, and autograd.
# Explain dynamic computation graphs and why they are useful for neural networks.
# Describe the full lifecycle of a training step in PyTorch, including forward pass, backward pass, gradient descent, and gradient reset.
# Explain in-place operations in detail, including when they are useful and when they break autograd.
# Compare PyTorch and NumPy from the point of view of scientific computing and deep learning.

In [3]:
import torch
import numpy as np
import random
import time

In [23]:
tnsr1D = torch.tensor([1,2,3], dtype=torch.float64, device="cuda")   
tnsr2D = torch.tensor([[1,2,3], [32,43,5]], dtype=torch.float32, device="cuda") 
tnsr3D = torch.tensor([[[1,2,3], [32,43,5]], [[11,22,33], [132,243,445]]], dtype=torch.float32, device="cuda")  
display("tensors: ")
# display(tnsr1D, tnsr1D.shape, tnsr1D.dtype, tnsr1D.device)
# display(tnsr2D, tnsr2D.shape, tnsr2D.dtype, tnsr2D.device)
display(tnsr3D, tnsr3D.shape, tnsr3D.dtype, tnsr3D.device)

'tensors: '

tensor([[[  1.,   2.,   3.],
         [ 32.,  43.,   5.]],

        [[ 11.,  22.,  33.],
         [132., 243., 445.]]], device='cuda:0')

torch.Size([2, 2, 3])

torch.float32

device(type='cuda', index=0)

In [24]:
display("val: ",tnsr3D[1,0,2])
display("row: ", tnsr2D[0])
display("col: ", tnsr2D[:,2])
display("sub metric: ", tnsr3D[0, :, 1:3])


'val: '

tensor(33., device='cuda:0')

'row: '

tensor([1., 2., 3.], device='cuda:0')

'col: '

tensor([3., 5.], device='cuda:0')

'sub metric: '

tensor([[ 2.,  3.],
        [43.,  5.]], device='cuda:0')

In [27]:
display(tnsr2D+tnsr2D)
display(tnsr1D.exp(), tnsr3D.mean(dim=1))

tensor([[ 2.,  4.,  6.],
        [64., 86., 10.]], device='cuda:0')

tensor([ 2.7183,  7.3891, 20.0855], device='cuda:0', dtype=torch.float64)

tensor([[ 16.5000,  22.5000,   4.0000],
        [ 71.5000, 132.5000, 239.0000]], device='cuda:0')

In [33]:
np_arr = np.array([[1, 2], [3, 4]])
torch_tensor = torch.tensor([[1, 2], [3, 4]])

# Addition
np_sum = np_arr + np_arr
torch_sum = torch_tensor + torch_tensor

# Conversion (NumPy ↔ Tensor)
converted_to_tensor = torch.from_numpy(np_arr) #shares memory
converted_to_numpy = torch_tensor.numpy() #shares memory
display(converted_to_tensor, converted_to_numpy)

# testing shared behavior
converted_to_numpy[0,0] = 10
display(torch_tensor)

# default numpy dtype
np.array([1.0, 2.0, 3.0]).dtype   # float64  ✅ default for floats
torch.tensor([1.0, 2.0, 3.0]).dtype  # float32 ✅ default for floats

tensor([[1, 2],
        [3, 4]])

array([[1, 2],
       [3, 4]])

tensor([[10,  2],
        [ 3,  4]])

torch.float32

In [30]:
# 5 is done in 4th

In [44]:
#6
arr3D = [[[-1, 2],[-2,-3]],[[3,4],[3,6]]]
tnsr3D = torch.tensor(arr3D)
display(tnsr3D.relu()) #out-of-place
tnsr3D.relu_()
display(tnsr3D) #in-place

tnsr3D = tnsr3D + 1 #create new object and rebind it to tnsr3D
display(tnsr3D)
tnsr3D += 1 #in-place
display(tnsr3D)


tensor([[[0, 2],
         [0, 0]],

        [[3, 4],
         [3, 6]]])

tensor([[[0, 2],
         [0, 0]],

        [[3, 4],
         [3, 6]]])

tensor([[[1, 3],
         [1, 1]],

        [[4, 5],
         [4, 7]]])

tensor([[[2, 4],
         [2, 2]],

        [[5, 6],
         [5, 8]]])

In [50]:
display(tnsr3D.device)
tnsr3D = tnsr3D.to("cuda", dtype=torch.float64) #out-of-place and rebind to tnsr3D
# tnsr3D.cpu() or tnsr3D.cuda is short hand for to() function
display(tnsr3D.device)

device(type='cuda', index=0)

device(type='cuda', index=0)

In [61]:
# benchmark
tnsr3D = torch.tensor([[random.randint(1,1000) for i in range(1000)] for i in range(1000)])
tnsr3Dcuda = tnsr3D.cuda()

a = time.time()
tnsr3D*tnsr3D
display(time.time()-a)
a = time.time()
tnsr3Dcuda*tnsr3Dcuda #async
torch.cuda.synchronize()

display(time.time()-a)

0.0

0.000990152359008789

In [62]:
import torch
import time

# -----------------------
# Config
# -----------------------
device = "cuda" if torch.cuda.is_available() else "cpu"
size = 5000   # increase to 10000+ for clearer GPU advantage
runs = 50

print(f"Using device: {device}")

# -----------------------
# Create tensors
# -----------------------
cpu_tensor = torch.randn(size, size)
gpu_tensor = cpu_tensor.to(device)

# -----------------------
# CPU Benchmark
# -----------------------
# warmup
for _ in range(10):
    cpu_tensor * cpu_tensor

start = time.time()
for _ in range(runs):
    cpu_tensor @ cpu_tensor
cpu_time = (time.time() - start) / runs

# -----------------------
# GPU Benchmark
# -----------------------
if device == "cuda":
    # warmup
    for _ in range(10):
        gpu_tensor * gpu_tensor

    torch.cuda.synchronize()

    start = time.time()
    for _ in range(runs):
        gpu_tensor @ gpu_tensor
    torch.cuda.synchronize()

    gpu_time = (time.time() - start) / runs
else:
    gpu_time = None

# -----------------------
# Results
# -----------------------
print(f"\nTensor size: {size} x {size}")
print(f"CPU time per op: {cpu_time:.6f} sec")

if gpu_time is not None:
    print(f"GPU time per op: {gpu_time:.6f} sec")
    print(f"Speedup (CPU/GPU): {cpu_time / gpu_time:.2f}x")
else:
    print("CUDA not available")

Using device: cuda

Tensor size: 5000 x 5000
CPU time per op: 0.589308 sec
GPU time per op: 0.037997 sec
Speedup (CPU/GPU): 15.51x


In [82]:
#9 and #11
x = torch.tensor([1,2,3],dtype=torch.float32, requires_grad=True)
y = (x**2).sum()
z = y**2
# y.backward()
# print(x.grad)
# x.grad.zero_()
z.backward() #causes second time grad as backward clears the graph that is used to calculate grad
print(x.grad)


tensor(14., grad_fn=<SumBackward0>)
tensor([ 56., 112., 168.])


In [13]:
#10
# search vs slope
# +/- the steps to get min cost function vs step big/small based on gradient (grad*lr)

# gradient 
x = torch.tensor(10.0, requires_grad=True)
lr = 0.01

for i in range(1000):
    f_x = x ** 2 + 10          # recompute from current x
    f_x.backward()        # compute gradient at current x

    with torch.no_grad():
        x -= lr * x.grad  # update x only

    x.grad.zero_()

print(f_x, x)

tensor(10., grad_fn=<AddBackward0>) tensor(1.6830e-08, requires_grad=True)


In [ ]:
#16, 14 gradient with detach(not no_grad())
x = torch.tensor(10.0, requires_grad=True)
lr = 0.01
x_detached = x.detach()
for i in range(1000):
    f_x = x ** 2 + 10          # recompute from current x
    f_x.backward()        # compute gradient at current x


    x_detached -= lr * x.grad  # update x only

    x.grad.zero_()

print(f_x, x)
# we can use clone to make seperate tensor, if we change x_detach, x will change

tensor(10., grad_fn=<AddBackward0>) tensor(1.6830e-08, requires_grad=True)


In [19]:
tnsr = torch.tensor([1,2,3], dtype=torch.float32)
tnsr.max()
tnsr

tensor([1., 2., 3.])