In [2]:
import torch    

In [5]:
x = torch.tensor(3.3, requires_grad=True)
y__x = x**2
y__x.retain_grad() #how to get grad of intermediate tensors
f__y = y__x**3
f__y.backward()
display(y__x.grad)
display(x.grad)



# we do backward on f(inputs) where inputs can have other inputs like inputs = y(x)
# backward traverses the computation graph in reverse and applies the chain rule at every node
# so for f(y(x)): df/dy is computed at y(x), and then df/dx = (df/dy)*(dy/dx) is accumulated at x
# to get df/dy we call .grad at y(x) level, and to get df/dx (chain rule already applied) we call .grad at x level

tensor(355.7762)

tensor(2348.1233)

In [6]:
# inplace operation doesn't work well with gradients

In [56]:
import random
# training loop of neural network

# setup (initlize input hidden and output layers)
# compute with intialized weights
# compute loss function
# compute gradient and based on that adjust weight
# repeat from step 3 wight updated weights

w = torch.tensor(100.0, requires_grad=True)
b = torch.tensor(100.0, requires_grad=True)
random.seed(34)
n = 5
inp = torch.tensor([[i] for i in range(n)], dtype=torch.float)
out = torch.tensor([[(7)*i + (43)] for i in range(n)])




epochs = 1000
learning_rate = 0.01
for epoch in range(epochs):
    pred =  w*inp + b
    # print(pred)
    # print(out)
    loss = torch.mean(torch.abs(pred - out))   
    loss.backward()
    # print(loss)
    with torch.no_grad():
        # print(w.grad*learning_rate)
        w -= w.grad*learning_rate
        # print(b.grad*learning_rate)
        b -= b.grad*learning_rate
     # Clear gradients
    w.grad.zero_()
    b.grad.zero_()
    # print()
        
    print("W: ", w, "B: ", b)



W:  tensor(99.9800, requires_grad=True) B:  tensor(99.9900, requires_grad=True)
W:  tensor(99.9600, requires_grad=True) B:  tensor(99.9800, requires_grad=True)
W:  tensor(99.9400, requires_grad=True) B:  tensor(99.9700, requires_grad=True)
W:  tensor(99.9200, requires_grad=True) B:  tensor(99.9600, requires_grad=True)
W:  tensor(99.9000, requires_grad=True) B:  tensor(99.9500, requires_grad=True)
W:  tensor(99.8800, requires_grad=True) B:  tensor(99.9400, requires_grad=True)
W:  tensor(99.8600, requires_grad=True) B:  tensor(99.9300, requires_grad=True)
W:  tensor(99.8400, requires_grad=True) B:  tensor(99.9200, requires_grad=True)
W:  tensor(99.8200, requires_grad=True) B:  tensor(99.9100, requires_grad=True)
W:  tensor(99.8000, requires_grad=True) B:  tensor(99.9000, requires_grad=True)
W:  tensor(99.7800, requires_grad=True) B:  tensor(99.8900, requires_grad=True)
W:  tensor(99.7600, requires_grad=True) B:  tensor(99.8800, requires_grad=True)
W:  tensor(99.7400, requires_grad=True) 

In [117]:
import torch.nn as nn

torch.manual_seed(34)
n = 5
inp = torch.tensor([[i] for i in range(n)], dtype=torch.float)
out = torch.tensor([[(7)*i + (43)] for i in range(n)], dtype=torch.float)

model = nn.Linear(1, 1, dtype=torch.float)

display(model.weight)
display(model.bias)
display(out.dtype)

pred = model(inp)
display(pred.dtype)

def train(model, criterion, optimizer, epoches=10000):
    for epoch in range(epoches):
        pred = model(inp)
        # print("keshav")
        # print(out, pred)
        loss = criterion(out, pred)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        

train(model, criterion=nn.MSELoss(), optimizer=torch.optim.SGD(model.parameters(), 0.01))
pred = model(inp)
print(model.weight)
print(out, pred)

# optmizer and model are indirectly linked, optmizer can change model weights(i.e. learning) using the iterator model.parameter provides



Parameter containing:
tensor([[0.7436]], requires_grad=True)

Parameter containing:
tensor([-0.7689], requires_grad=True)

torch.float32

torch.float32

Parameter containing:
tensor([[7.0001]], requires_grad=True)
tensor([[43.],
        [50.],
        [57.],
        [64.],
        [71.]]) tensor([[42.9997],
        [49.9998],
        [56.9999],
        [64.0000],
        [71.0001]], grad_fn=<AddmmBackward0>)


In [118]:
# Load training and test datasets
from torchvision import datasets, transforms
# True to download again
train_dataset = datasets.MNIST(root='./data', train=True, download=False)
test_dataset = datasets.MNIST(root='./data', train=False, download=False)


In [119]:
def preprocess_data():
    train_dataset.data = train_dataset.data.reshape(-1, 784)
    test_dataset.data = test_dataset.data.reshape(-1, 784)
preprocess_data()

print(train_dataset.data[0])
print(test_dataset.data[0])


tensor([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,
         18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 1

In [120]:
# print(train_dataset.targets[0])
# train_dataset.targets = torch.tensor([[0 if i!=j else 1 for i in range(10)] for j in train_dataset.targets])
# test_dataset.targets = torch.tensor([[0 if i!=j else 1 for i in range(10)] for j in test_dataset.targets])

# print(train_dataset.targets[0])

In [ ]:
model = nn.Sequential(
    nn.Linear(784, 50),  # input layer:  784 → 50
    nn.ReLU(),           # ✓ no arguments
    nn.Linear(50, 10),   # output layer: 50  → 10 (one per digit)
)

criterion = nn.CrossEntropyLoss()
# Softmax → converts raw scores (logits) into probabilities
# Negative Log Likelihood → penalizes wrong predictions

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
# arg1 = torch.randn(1, 10)
# print(arg1)
# print(criterion(arg1, torch.tensor([5])))


print(train_dataset.data[0])
train_dataset.data = train_dataset.data.float() / 255.0
test_dataset.data  = test_dataset.data.float() / 255.0
print(train_dataset.data[0])
train_dataset.targets = train_dataset.targets.long()
test_dataset.targets  = test_dataset.targets.long()


def train(model, criterion, optimizer, epoches=10000):
    min_validation_error = float("inf")

    patience = 20
    counter = 0

    for epoch in range(epoches):
        optimizer.zero_grad()
        pred = model(train_dataset.data)
        # print(out, pred)
        loss = criterion(pred, train_dataset.targets)
        loss.backward()
        optimizer.step()
        with torch.no_grad():
            test_pred = model(test_dataset.data)
            validation_error = criterion(test_pred, test_dataset.targets)
        if validation_error < min_validation_error:
            min_validation_error = validation_error
            counter = 0
        else:
            counter += 1

        if counter >= patience:
            break

        print(f"epoch {epoch}/{epoches}: loss is {loss.item():.6f} | validation_error is {validation_error.item()}")

    print(f"epoch {epoch}/{epoches}: loss is {loss.item():.6f} | validation_error is {validation_error.item()}")


train(model, criterion, optimizer)


tensor([0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+

In [122]:
test_pred = model(test_dataset.data)

criterion(test_pred, test_dataset.targets)

tensor(0.2921, grad_fn=<NllLossBackward0>)

In [ ]:
# 3. Normalize inputs
# Neural nets train better when values are small and centered.

In [ ]:
# Lab 1 — Linear regression with raw tensors + autograd
# Load California housing, split into train/valid/test, and turn each split into float tensors.
# Normalize the features using tensor operations only (no StandardScaler). Compute the statistics on the training set, then apply them everywhere.
# The raw targets come out as 1D. Reshape them so predictions and targets are the same shape. Figure out which shape the math actually wants.
# Create a weight tensor and a bias tensor as trainable parameters. Initialize one randomly and the other at zero.
# Write a full batch gradient descent loop: predict, compute MSE, backprop, update under a no-grad context, reset gradients, print the loss each epoch.
# Use the trained parameters to predict a few new instances.
# Go further: Sweep the learning rate across a few orders of magnitude — find where it diverges, where it crawls, where it's just right. Does initializing the bias randomly instead of at zero change anything here? Why might that change for a deeper network?


from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
import torch


try:
    dataset = fetch_california_housing()
except Exception as e:
    raise RuntimeError("failed to load data") from e

print(dataset.feature_names)

data = dataset.data
# print(data)

X_train, X_test, y_train, y_test = train_test_split(data, dataset.target)
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)

# print(X_train)
# print(X_test)
# print(y_test)
# print(y_train)





['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']


In [ ]:
print(X_train)
print(X_test)
print(y_test)
print(y_train)

class customNeuralNetwork(torch.nn.modules):
    def __init__():
        

customNN = customNeuralNetwork()

SyntaxError: incomplete input (1274629678.py, line 6)

In [ ]:
# important

class Noun:
    def __init__(self, type="thing"):
        self.type = type

class Bag:
    def __init__(self):
        self.a = 1
        self.b = "hello"
        self.noun = Noun()

bag = Bag()
print(vars(bag))    # {'a': 1, 'b': 'hello'}

{'a': 1, 'b': 'hello', 'noun': <__main__.Noun object at 0x00000240AF8BF920>}
