In [34]:
import torch    

In [35]:
x = torch.tensor(3.3, requires_grad=True)
y__x = x**2
y__x.retain_grad() #how to get grad of intermediate tensors
f__y = y__x**3
f__y.backward()
display(y__x.grad)
display(x.grad)



# we do backward on f(inputs) where inputs can have other inputs like inputs = y(x)
# backward traverses the computation graph in reverse and applies the chain rule at every node
# so for f(y(x)): df/dy is computed at y(x), and then df/dx = (df/dy)*(dy/dx) is accumulated at x
# to get df/dy we call .grad at y(x) level, and to get df/dx (chain rule already applied) we call .grad at x level

tensor(355.7762)

tensor(2348.1233)

In [36]:
# inplace operation doesn't work well with gradients

In [37]:
import random
# training loop of neural network

# setup (initlize input hidden and output layers)
# compute with intialized weights
# compute loss function
# compute gradient and based on that adjust weight
# repeat from step 3 wight updated weights

w = torch.tensor(100.0, requires_grad=True)
b = torch.tensor(100.0, requires_grad=True)
random.seed(34)
n = 5
inp = torch.tensor([[i] for i in range(n)], dtype=torch.float)
out = torch.tensor([[(7)*i + (43)] for i in range(n)])




epochs = 1000
learning_rate = 0.01
for epoch in range(epochs):
    pred =  w*inp + b
    # print(pred)
    # print(out)
    loss = torch.mean(torch.abs(pred - out))   
    loss.backward()
    # print(loss)
    with torch.no_grad():
        # print(w.grad*learning_rate)
        w -= w.grad*learning_rate
        # print(b.grad*learning_rate)
        b -= b.grad*learning_rate
     # Clear gradients
    w.grad.zero_()
    b.grad.zero_()
    # print()
        
    print("W: ", w, "B: ", b)



W:  tensor(99.9800, requires_grad=True) B:  tensor(99.9900, requires_grad=True)
W:  tensor(99.9600, requires_grad=True) B:  tensor(99.9800, requires_grad=True)
W:  tensor(99.9400, requires_grad=True) B:  tensor(99.9700, requires_grad=True)
W:  tensor(99.9200, requires_grad=True) B:  tensor(99.9600, requires_grad=True)
W:  tensor(99.9000, requires_grad=True) B:  tensor(99.9500, requires_grad=True)
W:  tensor(99.8800, requires_grad=True) B:  tensor(99.9400, requires_grad=True)
W:  tensor(99.8600, requires_grad=True) B:  tensor(99.9300, requires_grad=True)
W:  tensor(99.8400, requires_grad=True) B:  tensor(99.9200, requires_grad=True)
W:  tensor(99.8200, requires_grad=True) B:  tensor(99.9100, requires_grad=True)
W:  tensor(99.8000, requires_grad=True) B:  tensor(99.9000, requires_grad=True)
W:  tensor(99.7800, requires_grad=True) B:  tensor(99.8900, requires_grad=True)
W:  tensor(99.7600, requires_grad=True) B:  tensor(99.8800, requires_grad=True)
W:  tensor(99.7400, requires_grad=True) 

In [38]:
import torch.nn as nn

torch.manual_seed(34)
n = 5
inp = torch.tensor([[i] for i in range(n)], dtype=torch.float)
out = torch.tensor([[(7)*i + (43)] for i in range(n)], dtype=torch.float)

model = nn.Linear(1, 1, dtype=torch.float)

display(model.weight)
display(model.bias)
display(out.dtype)

pred = model(inp)
display(pred.dtype)

def train(model, criterion, optimizer, epoches=10000):
    for epoch in range(epoches):
        pred = model(inp)
        # print("keshav")
        # print(out, pred)
        loss = criterion(out, pred)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        

train(model, criterion=nn.MSELoss(), optimizer=torch.optim.SGD(model.parameters(), 0.01))
pred = model(inp)
print(model.weight)
print(out, pred)

# optmizer and model are indirectly linked, optmizer can change model weights(i.e. learning) using the iterator model.parameter provides



Parameter containing:
tensor([[0.7436]], requires_grad=True)

Parameter containing:
tensor([-0.7689], requires_grad=True)

torch.float32

torch.float32

Parameter containing:
tensor([[7.0001]], requires_grad=True)
tensor([[43.],
        [50.],
        [57.],
        [64.],
        [71.]]) tensor([[42.9997],
        [49.9998],
        [56.9999],
        [64.0000],
        [71.0001]], grad_fn=<AddmmBackward0>)


In [39]:
# Load training and test datasets
from torchvision import datasets, transforms
# True to download again
train_dataset = datasets.MNIST(root='./data', train=True, download=False)
test_dataset = datasets.MNIST(root='./data', train=False, download=False)


In [40]:
def preprocess_data():
    train_dataset.data = train_dataset.data.reshape(-1, 784)
    test_dataset.data = test_dataset.data.reshape(-1, 784)
preprocess_data()

print(train_dataset.data[0])
print(test_dataset.data[0])


tensor([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,
         18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 1

In [41]:
# print(train_dataset.targets[0])
# train_dataset.targets = torch.tensor([[0 if i!=j else 1 for i in range(10)] for j in train_dataset.targets])
# test_dataset.targets = torch.tensor([[0 if i!=j else 1 for i in range(10)] for j in test_dataset.targets])

# print(train_dataset.targets[0])

In [42]:
model = nn.Sequential(
    nn.Linear(784, 50),  # input layer:  784 → 50
    nn.ReLU(),           # ✓ no arguments
    nn.Linear(50, 10),   # output layer: 50  → 10 (one per digit)
)

criterion = nn.CrossEntropyLoss()
# Softmax → converts raw scores (logits) into probabilities
# Negative Log Likelihood → penalizes wrong predictions

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
# arg1 = torch.randn(1, 10)
# print(arg1)
# print(criterion(arg1, torch.tensor([5])))


print(train_dataset.data[0])
train_dataset.data = train_dataset.data.float() / 255.0
test_dataset.data  = test_dataset.data.float() / 255.0
print(train_dataset.data[0])
train_dataset.targets = train_dataset.targets.long()
test_dataset.targets  = test_dataset.targets.long()


def train(model, criterion, optimizer, epoches=10000):
    min_validation_error = float("inf")

    patience = 20
    counter = 0

    for epoch in range(epoches):
        optimizer.zero_grad()
        pred = model(train_dataset.data)
        # print(out, pred)
        loss = criterion(pred, train_dataset.targets)
        loss.backward()
        optimizer.step()
        with torch.no_grad():
            test_pred = model(test_dataset.data)
            validation_error = criterion(test_pred, test_dataset.targets)
        if validation_error < min_validation_error:
            min_validation_error = validation_error
            counter = 0
        else:
            counter += 1

        if counter >= patience:
            break

        print(f"epoch {epoch}/{epoches}: loss is {loss.item():.6f} | validation_error is {validation_error.item()}")

    print(f"epoch {epoch}/{epoches}: loss is {loss.item():.6f} | validation_error is {validation_error.item()}")


train(model, criterion, optimizer)


tensor([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,
         18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 1

KeyboardInterrupt: 

In [ ]:
test_pred = model(test_dataset.data)

criterion(test_pred, test_dataset.targets)

tensor(0.2921, grad_fn=<NllLossBackward0>)

In [ ]:
# 3. Normalize inputs
# Neural nets train better when values are small and centered.

In [ ]:
# Lab 1 — Linear regression with raw tensors + autograd
# Load California housing, split into train/valid/test, and turn each split into float tensors.
# Normalize the features using tensor operations only (no StandardScaler). Compute the statistics on the training set, then apply them everywhere.
# The raw targets come out as 1D. Reshape them so predictions and targets are the same shape. Figure out which shape the math actually wants.
# Create a weight tensor and a bias tensor as trainable parameters. Initialize one randomly and the other at zero.
# Write a full batch gradient descent loop: predict, compute MSE, backprop, update under a no-grad context, reset gradients, print the loss each epoch.
# Use the trained parameters to predict a few new instances.
# Go further: Sweep the learning rate across a few orders of magnitude — find where it diverges, where it crawls, where it's just right. Does initializing the bias randomly instead of at zero change anything here? Why might that change for a deeper network?


from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
import torch


try:
    dataset = fetch_california_housing()
except Exception as e:
    raise RuntimeError("failed to load data") from e

print(dataset.feature_names)

data = dataset.data
# print(data)

X_train, X_test, y_train, y_test = train_test_split(data, dataset.target)
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)

# print(X_train)
# print(X_test)
# print(y_test)
# print(y_train)

#             what is normalization?
# # x-x_min/(x_max-x_min)
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler

# scaler = StandardScaler()

# X_train = scaler.fit_transform(X_train.numpy())
# X_test = scaler.transform(X_test.numpy())

# X_train = torch.tensor(X_train, dtype=torch.float32)
# X_test = torch.tensor(X_test, dtype=torch.float32)
num_features = len(X_train[0])

mins = [min(row[j] for row in X_train) for j in range(num_features)]
maxs = [max(row[j] for row in X_train) for j in range(num_features)]

for row in X_train:
    for j in range(num_features):
        row[j] = (row[j] - mins[j]) / (maxs[j] - mins[j])# we are using train data for test normalization aswell. this is important

for row in X_test:
    for j in range(num_features):
        row[j] = (row[j] - mins[j]) / (maxs[j] - mins[j])


print(X_train)

['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']
tensor([[ 1.4254e-01,  3.9216e-01,  3.0147e-02,  ...,  1.4099e-03,
          6.2380e-01,  3.7948e-01],
        [ 2.1317e-01,  5.8824e-01,  1.8243e-02,  ...,  9.7133e-04,
          5.1541e-01,  2.2410e-01],
        [ 2.0742e-01,  4.7059e-01,  2.8827e-02,  ...,  1.6624e-03,
          8.9160e-01,  2.3904e-02],
        ...,
        [ 3.1799e+00,         nan,  5.6566e+00,  ...,  3.5202e+00,
          3.4080e+01, -1.1733e+02],
        [ 3.5852e+00,         nan,  5.4412e+00,  ...,  2.7647e+00,
          3.8650e+01, -1.2130e+02],
        [ 4.2670e+00,         nan,  5.5316e+00,  ...,  2.6468e+00,
          3.7680e+01, -1.2214e+02]])


In [ ]:
import torch
learning_rate = 0.01
class customNeuralNetwork(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.weights = torch.nn.Parameter( #model.parameters() will show this if we use this
            torch.tensor([1.0, 2.0, 3.0, 1.0, 2.0, 1.0, 2.0, 3.0], dtype=torch.float32)
        )
        self.bias = torch.nn.Parameter(torch.tensor(1.0, dtype=torch.float32))

    def forward(self, inputs):
        # inputs shape: [batch_size, 8]
        # output shape: [batch_size]
        print("input", inputs[0], self.weights)
        return inputs @ self.weights + self.bias


model = customNeuralNetwork()

for step in range(100):
    model.zero_grad()
    y_train_pred = model(X_train) #this is why we are using torch.nn.modules, to use model(instance of customNeuralNetwork) as a function
    # print(y_train_pred)
    loss = ((y_train_pred - y_train)**2).mean()
    # print(loss)
    loss.backward()
    with torch.no_grad():
        # in-place update keeps these as nn.Parameter objects; reassigning
        # model.weights = ... would replace the Parameter with a plain Tensor
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
    
print([parameter for parameter in model.parameters()])

print("hello")

In [ ]:
# Lab 2 — Same model, high-level API
# Replace your hand-rolled weight/bias with a single built-in linear layer. Inspect its weight and bias attributes. Compare the weight's shape to the tensor you made by hand in Lab 1 — they're related by a transpose. Make sure you can explain why.
# Iterate over the module's parameters two ways: anonymously, and as name/value pairs.
# Call the model on a small batch as if it were a function. Look at the result's grad_fn. What does calling the module actually trigger under the hood?
# Attach a hook that fires whenever the module runs, then remove it. Confirm it does not fire if you bypass the normal call path — and form an opinion on why you should never bypass it.
# Swap your manual update + zero-grad lines for an optimizer and a loss-function object. Wrap it all in a reusable training function.
# Train, predict, and compare numbers against Lab 1. They'll be close but not identical — track down the reason.
# Go further: The loss object is also a "module." What else in this library turns out to be a module? Why is that a useful design choice?



In [21]:
# important
# 1. 
class Noun:
    def __init__(self, type="thing"):
        self.type = type

class Bag:
    def __init__(self):
        self.a = 1
        self.b = "hello"
        self.noun = Noun()

bag = Bag()
print(vars(bag))    # {'a': 1, 'b': 'hello'}

# 2.
class Doubler:
    def __call__(self, x):
        return x * 2

f = Doubler()
print(f(10))    # 20 — calling the instance runs __call__

# 3.

class Doubler:
    def __call__(self, x):
        return x * 2

f = Doubler()
print(f(10))    # 20 — calling the instance runs __call__
# super().__init__(...) means: "run my parent class's constructor." If you forget it, the parent's setup never happens. This matters enormously in PyTorch — nn.Module.__init__ sets up the internal bookkeeping that tracks your parameters. Forget super().__init__() in a model and you get a confusing error the moment you try to use it.


# 4.
# Calling .backward() on a scalar walks that record in reverse and computes the derivative of that scalar with respect to every tensor that has requires_grad=True:




{'a': 1, 'b': 'hello', 'noun': <__main__.Noun object at 0x0000020F86C168D0>}
20
20


In [14]:
import torch

# --- fake data: y = 4x + 3, plus noise ---
x = torch.linspace(0, 10, 100).reshape(-1, 1)          # shape (100, 1)
y_true = 4 * x + 3 + torch.randn(100, 1) * 0.5

# --- "model": just two tensors ---
w = torch.randn(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

learning_rate = 0.01

for step in range(1000):
    # 1. forward: compute predictions
    y_pred = x * w + b                                  # broadcasting does the work

    # 2. loss: mean squared error, written out
    loss = ((y_pred - y_true) ** 2).mean()
    print(loss)
    # 3. backward: fills w.grad and b.grad
    loss.backward()
    print(w.grad)
    # 4. update: gradient descent by hand
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
    w.grad.zero_()
    b.grad.zero_()

    if step % 200 == 0:
        print(f"step {step}: loss={loss.item():.4f}, w={w.item():.3f}, b={b.item():.3f}")

# w ends up near 4, b near 3

tensor(402.5222, grad_fn=<MeanBackward0>)
tensor([-231.5355])
step 0: loss=402.5222, w=3.309, b=0.361
tensor(41.5071, grad_fn=<MeanBackward0>)
tensor([-72.7924])
tensor(5.6876, grad_fn=<MeanBackward0>)
tensor([-22.8000])
tensor(2.1215, grad_fn=<MeanBackward0>)
tensor([-7.0565])
tensor(1.7545, grad_fn=<MeanBackward0>)
tensor([-2.0990])
tensor(1.7049, grad_fn=<MeanBackward0>)
tensor([-0.5384])
tensor(1.6869, grad_fn=<MeanBackward0>)
tensor([-0.0475])
tensor(1.6721, grad_fn=<MeanBackward0>)
tensor([0.1065])
tensor(1.6579, grad_fn=<MeanBackward0>)
tensor([0.1544])
tensor(1.6438, grad_fn=<MeanBackward0>)
tensor([0.1689])
tensor(1.6298, grad_fn=<MeanBackward0>)
tensor([0.1728])
tensor(1.6160, grad_fn=<MeanBackward0>)
tensor([0.1735])
tensor(1.6023, grad_fn=<MeanBackward0>)
tensor([0.1731])
tensor(1.5887, grad_fn=<MeanBackward0>)
tensor([0.1724])
tensor(1.5753, grad_fn=<MeanBackward0>)
tensor([0.1716])
tensor(1.5620, grad_fn=<MeanBackward0>)
tensor([0.1708])
tensor(1.5489, grad_fn=<MeanBackwa