In [1]:
import torch

In [ ]:
arr = [[1.0,2,3], [4,5,6]] 
tensor1 = torch.tensor(arr)
print(tensor1)
print(tensor1.shape)
print(tensor1.dtype)
# uint for image w,h,(r,g,b)
# slicing
# tnsr[0:3:2, 1:, 4] is tnsr[slice(0, 3, 2), slice(1, None), 4]



tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
torch.float32


In [ ]:
# What does dim = 0, 1, 2 mean for tnsr3D.mean(dim=1)?
# It specifies the dimension along which the operation (e.g., mean, exp) is applied.

# For example, to compute the mean across rows or columns in a tensor.

# Suppose: tnsr3D.shape = (A, B, C)
# Then:
#   dim = 0 → corresponds to A
#   dim = 1 → corresponds to B
#   dim = 2 → corresponds to C

# When we apply an operation with dim = k, that dimension is reduced (collapsed).

# Example:
# tnsr3D.mean(dim=0) → collapses dimension A
# Resulting shape: (B, C)

# tnsr3D.mean(dim=1) → collapses dimension B
# Resulting shape: (A, C)

# tnsr3D.mean(dim=2) → collapses dimension C
# Resulting shape: (A, B)

In [3]:
tensor_max = tensor1.max(dim=0).values # 0 -> max of each column | 1-> row; just like how we will use for loop to access each value

In [4]:
tensor_max

tensor([4., 5., 6.])

In [5]:
import numpy
tensor1.numpy().dtype

dtype('float32')

In [6]:
tensor1[:, 1] = -99 #":" means iterate like we usually do in for loop(we iterate through rows then we access row element) and change the 1st element of each row 
tensor1

tensor([[  1., -99.,   3.],
        [  4., -99.,   6.]])

In [7]:
tensor1.relu_()

tensor([[1., 0., 3.],
        [4., 0., 6.]])

In [8]:
tensor1.mean()

tensor(2.3333)

In [9]:
print(torch.cuda.is_available())

True


In [10]:
torch.backends.mps.is_available()

False

In [11]:
m = torch.rand((1000,1000))
%timeit m@m

5.34 ms ± 1.56 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
m = torch.rand((1000,1000), device="cuda")
%timeit m@m

200 μs ± 15.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [19]:
# 5.34 ms per loop → mean execution time

# On average, one execution of your code took 5.34 milliseconds.

# ± 1.56 ms → standard deviation

# This measures variation between the 7 runs.

# Larger value = timings were less consistent.

# 7 runs

# %timeit repeated the whole experiment 7 separate times.

# 100 loops each

# In each run, your code executed 100 times, and the average per loop was computed.

In [23]:
x = torch.tensor(5.0, requires_grad=True)
f = x**2
f.backward()
print(f)
x.grad

tensor(25., grad_fn=<PowBackward0>)


tensor(10.)

In [24]:
x.grad.zero_() #reset grad

tensor(0.)